os: linux
group: stable
dist: trusty
sudo: required
language: node_js
node_js: 6

branches:
  only: master

before_script:
  - mkdir -p coverage
  - npm install -g istanbul codecov

script:
  - npm run coverage

after_success:
  - codecov

notifications:
  email: bianco@javanile.org
